title:
  en: "Phil Rigovanov"
  ru: "Филипп Ригованов"
author:
  en: "Phil Rigovanov"
  ru: "Филипп Ригованов"
description:
  en: "“For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.” —&npsp;John&NoBreak;3:16"
  ru: "«Ибо так возлюбил Бог мир, что отдал Сына Своего Единородного, дабы всякий, верующий в Него, не погиб, но имел жизнь вечную.» —&npsp;Иоанна&NoBreak;3:16"
#description: "Made with <b style=\"color: #f45;\">❤</b> by <b><a href=\"https://github.com/a1ip\">@a1ip</a></b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
remote_theme: niklasbuschmann/contrast@v2.8
url: "https://rigovanov.ru"
bibleref: false
# baseurl: "/contrast/" # does not include hostname

links:
  church: "https://novchurch.ru"
  vcard: "https://phil.rigovanov.ru"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "about.md", icon: address-card}
  - {file: "library.md", icon: book-open} # need to add link to http://rigovanov.ru/cv/  fontawesome icons for cv: id-card, newspaper, money-check

external:                    # see http://fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/a1ip"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/phil_rigovanov"}
  - {title: Tumblr, icon: tumblr, url: "https://rigovanov.tumblr.com"}
  - {title: "Bible.com", icon: bible, url: "https://my.bible.com/users/a1ip"}
  - {title: Telegram, icon: telegram, url: "https://t.me/rigovanov"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
  disqus_shortname: "a1ip"                # see https://disqus.com/
#  isso_domain: ""                  # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-remote-theme

defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "assets" # Exclude from sitemap.xml
    values:
      sitemap:
        exclude: "yes"
  -
    scope:
      path: "404.html" # Exclude from sitemap.xml
    values:
      sitemap:
        exclude: "yes"
  -
    scope:
      path: "README.md" # Exclude from sitemap.xml
    values:
      sitemap:
        exclude: "yes"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
    
sass:
  style: compressed


socials:                    # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:phil@rigovanov.ru"}
  - {title: Github, icon: github, url: "https://github.com/a1ip"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
  - {title: "Bible.com", icon: bible, url: "https://my.bible.com/users/a1ip"}
  - {title: Instagram, icon: instagram, url: "https://instagram.com/a1ip"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/phil_rigovanov"}
  - {title: Facebook, icon: facebook, url: "https://facebook.com/rigovanov"}
  - {title: VK, icon: vk, url: "https://vk.com/rigovanov"}
  - {title: Tumblr, icon: tumblr, url: "https://rigovanov.tumblr.com"}
  - {title: Telegram, icon: telegram, url: "http://t.me/rigovanov"}
  - {title: "G+", icon: google-plus-g, url: "https://plus.google.com/u/0/+PhilippeRigovanov"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/rigovanov/"}
  - {title: Dribbble, icon: dribbble, url: "https://dribbble.com/a1ip"}
  - {title: Behance, icon: behance, url: "https://www.behance.net/rigovanov"}
  - {title: Pinterest, icon: pinterest, url: "https://pinterest.com/philrigovanov/"}
  - {title: Flickr, icon: flickr, url: "https://www.flickr.com/photos/a1ip/"}
  - {title: 500px, icon: 500px, url: "https://500px.com/a1ip"}
  - {title: YouTube, icon: youtube, url: "https://www.youtube.com/user/philrigovanov"}
  - {title: Vimeo, icon: vimeo, url: "https://vimeo.com/rigovanov"}
  - {title: SoundCloud, icon: soundcloud, url: "https://soundcloud.com/a1ip/"}
  - {title: Twitch, icon: twitch, url: "https://www.twitch.tv/a1ip"}
  - {title: Keybase, icon: keybase, url: "https://keybase.io/a1ip"}
